### ISSUE TITLE
Checklist update

### ISSUE THREAD

**Issue by gautada** [gautada/dynip-container#4]
- [X] README conforms to the [gist](https://gist.github.com/gautada/ec549c846e8e50daf355d01b06eb0665)
- [X] .gitignore conforms to the [gist](https://gist.github.com/gautada/3a0a4a76d3c7e4539e71fc02c7f599ad)
- [X] Confirm the drone.yml file
- [X] Volume folders are present (development-volume & backup-volume)
- [X] docker-compose(.yml) works
- [x] Manifest folder present (and origin to private repository is correct
- [x] Issue List is linked to proper URI
- [x] Signoff ({date and signature of last check})
- [x] Confirm backup (maybe add to testing layer)
- [ ] Confirm healthcheck (maybe add to testing layer)
- [x] Regenerate all architecture images
- [x] Decouple alpine upstream image in `Containerfile`, `docker-compose.yml`, and `drone.yml`

**Comment by gautada** [comment]
Signing off since the health check is not ready to go.
